"""create optimization tables

Revision ID: 67d1740a6005
Revises: b7a6d77ce490
Create Date: 2026-08-30 15:34:08.669426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67d1740a6005'
down_revision: Union[str, Sequence[str], None] = 'b7a6d77ce490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('payload_id', sa.UUID(), nullable=True),
    sa.Column('selected_candidate_id', sa.UUID(), nullable=True),
    sa.Column('optimization_algorithm', sa.String(length=50), nullable=False),
    sa.Column('objective_function', sa.String(length=100), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['payload_id'], ['payloads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_iterations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('optimization_run_id', sa.UUID(), nullable=False),
    sa.Column('iteration_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('selected_candidate_id', sa.UUID(), nullable=True),
    sa.Column('optimizer_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iteration_id', sa.UUID(), nullable=False),
    sa.Column('method_id', sa.UUID(), nullable=False),
    sa.Column('candidate_number', sa.Integer(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['iteration_id'], ['optimization_iterations.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['embedding_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objective_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_configuration_id', sa.UUID(), nullable=False),
    sa.Column('objective_name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('metric_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_configuration_id'], ['candidate_configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objective_scores')
    op.drop_table('candidate_configurations')
    op.drop_table('optimization_iterations')
    op.drop_table('optimization_runs')
    # ### end Alembic commands ###
