"""create steganography tables

Revision ID: 8db8ffbdebe7
Revises: e23982a15937
Create Date: 2026-08-30 15:21:35.225066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8db8ffbdebe7'
down_revision: Union[str, Sequence[str], None] = 'e23982a15937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('method_id', sa.UUID(), nullable=False),
    sa.Column('configuration_name', sa.String(length=100), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('region_strategy', sa.String(length=50), nullable=False),
    sa.Column('payload_allocation_strategy', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['method_id'], ['embedding_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steganography_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cover_image_id', sa.UUID(), nullable=False),
    sa.Column('stego_image_id', sa.UUID(), nullable=True),
    sa.Column('payload_id', sa.UUID(), nullable=True),
    sa.Column('configuration_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload_capacity_bytes', sa.BigInteger(), nullable=True),
    sa.Column('psnr', sa.Float(), nullable=True),
    sa.Column('ssim', sa.Float(), nullable=True),
    sa.Column('extraction_accuracy', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('extraction_accuracy IS NULL OR (extraction_accuracy >= 0 AND extraction_accuracy <= 1)', name='ck_stego_extraction_accuracy_range'),
    sa.CheckConstraint('payload_capacity_bytes IS NULL OR payload_capacity_bytes >= 0', name='ck_stego_payload_capacity_nonnegative'),
    sa.CheckConstraint('processing_time_ms IS NULL OR processing_time_ms >= 0', name='ck_stego_processing_time_nonnegative'),
    sa.CheckConstraint('psnr IS NULL OR psnr >= 0', name='ck_stego_psnr_nonnegative'),
    sa.CheckConstraint('ssim IS NULL OR (ssim >= 0 AND ssim <= 1)', name='ck_stego_ssim_range'),
    sa.ForeignKeyConstraint(['configuration_id'], ['embedding_configurations.id'], ),
    sa.ForeignKeyConstraint(['cover_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['payload_id'], ['payloads.id'], ),
    sa.ForeignKeyConstraint(['stego_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embedding_regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('region_index', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('allocation_ratio', sa.Float(), nullable=True),
    sa.Column('embedding_score', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('allocation_ratio IS NULL OR (allocation_ratio >= 0 AND allocation_ratio <= 1)', name='ck_embedding_region_allocation_range'),
    sa.CheckConstraint('embedding_score IS NULL OR (embedding_score >= 0 AND embedding_score <= 1)', name='ck_embedding_region_score_range'),
    sa.CheckConstraint('height > 0', name='ck_embedding_region_height_positive'),
    sa.CheckConstraint('region_index >= 0', name='ck_embedding_region_index_nonnegative'),
    sa.CheckConstraint('width > 0', name='ck_embedding_region_width_positive'),
    sa.CheckConstraint('x >= 0', name='ck_embedding_region_x_nonnegative'),
    sa.CheckConstraint('y >= 0', name='ck_embedding_region_y_nonnegative'),
    sa.ForeignKeyConstraint(['session_id'], ['steganography_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'region_index', name='uq_embedding_region_session_index')
    )
    op.create_table('extraction_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('extracted_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('extracted_payload_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('integrity_verified', sa.Boolean(), nullable=True),
    sa.Column('processing_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('accuracy IS NULL OR (accuracy >= 0 AND accuracy <= 1)', name='ck_extraction_accuracy_range'),
    sa.CheckConstraint('extracted_size_bytes IS NULL OR extracted_size_bytes >= 0', name='ck_extraction_size_nonnegative'),
    sa.CheckConstraint('processing_time_ms IS NULL OR processing_time_ms >= 0', name='ck_extraction_processing_time_nonnegative'),
    sa.ForeignKeyConstraint(['session_id'], ['steganography_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extraction_records')
    op.drop_table('embedding_regions')
    op.drop_table('steganography_sessions')
    op.drop_table('embedding_configurations')
    # ### end Alembic commands ###
