"""add payload storage path

Revision ID: 99cb65980aee
Revises: 0dc94a986be3
Create Date: 2026-09-01 20:50:35.689883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99cb65980aee'
down_revision: Union[str, Sequence[str], None] = '0dc94a986be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payloads', sa.Column('storage_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payloads', 'storage_path')
    # ### end Alembic commands ###
